# Generated by Django 5.1.3 on 2024-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sent_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
