# Generated by Django 5.1.3 on 2024-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFirebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='fzfjagqWTjuamo6F_7AXgV:APA91bFbq_nyQccaXtLGNhn3wxiZZZWdrp-vfameXd_2l9TvN54bbuWiS0yS2OV0WIKSbQaoHXMtFl49NzGXUKppDjClOWyrDgFIKtlNuIAnk4qcsa7FehP5PajMuQpQgApmBi1C42pT', max_length=255)),
            ],
        ),
    ]
